/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.siebel.config;

import org.mule.api.MuleEvent;
import org.mule.construct.SimpleFlowConstruct;
import org.mule.module.siebel.transformers.SiebelPropertySetToXmlStringRemoteTestCase;
import org.mule.tck.FunctionalTestCase;

import com.siebel.data.SiebelPropertySet;

public class SiebelRemoteXmlTestCase extends FunctionalTestCase {
	
	@Override
	protected String getConfigResources() {
		return "siebel-remote-xml-config.xml";
	}

	private SimpleFlowConstruct lookupFlowConstruct(String name) {
		return (SimpleFlowConstruct) muleContext.getRegistry().lookupFlowConstruct(name);
	}
	
    public void testRemoteXml() throws Exception
    {
    	SiebelPropertySetToXmlStringRemoteTestCase tc = new SiebelPropertySetToXmlStringRemoteTestCase();
    	String str = (String)tc.getResultData();
    	
		SimpleFlowConstruct flow = lookupFlowConstruct("remoteXmlFlow");
		MuleEvent event = getTestEvent(str);
		MuleEvent responseEvent = flow.process(event);

		SiebelPropertySet result = responseEvent.getMessage().getPayload(SiebelPropertySet.class);
		assertTrue(tc.compareRoundtripResults(tc.getTestData(), result));
    }
}
