/**
 * This file was automatically generated by the Mule Cloud Connector Development Kit
 */
package org.mule.module.siebel.config;

import org.mule.api.MuleEvent;
import org.mule.construct.SimpleFlowConstruct;
import org.mule.tck.FunctionalTestCase;

import com.siebel.data.SiebelPropertySet;

public class SiebelNamespaceHandlerTestCase extends FunctionalTestCase {
	@Override
	protected String getConfigResources() {
		return "siebel-namespace-config.xml";
	}

	public void testSendMessageToFlow() throws Exception {
		SiebelPropertySet payload = new SiebelPropertySet();
		payload.setValue("Please echo this");
		SimpleFlowConstruct flow = lookupFlowConstruct("echoFlow");
		MuleEvent event = getTestEvent(payload);
		MuleEvent responseEvent = flow.process(event);
		SiebelPropertySet result = responseEvent.getMessage().getPayload(SiebelPropertySet.class);
		assertEquals(payload.getValue(), result.getValue());
	}

	private SimpleFlowConstruct lookupFlowConstruct(String name) {
		return (SimpleFlowConstruct) muleContext.getRegistry().lookupFlowConstruct(name);
	}
}
